### ISSUE TITLE
sslCertificateType Required for All Endpoints

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [stoiveyp/Alexa.NET.Management#51]
Within Region and Permissions there are endpoints for the URI

These both require sslCertificateType to pass certification in the Amazon Aleexa skills portal (took me ages to find a support link that gave clues to this)

Schema passes without but change EndPoint to EndPointWithSSL to allow manual editing and update of the model and "Publish Model" for example in the UWPApp example code project

**Comment by stoiveyp** [comment]
Hi @Crispin-at-Linknode - I'm not sure what you're asking for.

SSL Isn't required on Lambda ARN endpoints - but it's in the CustomApiEndpoint class. Could you point me to whereabouts in the schema you believe it's missing so I can investigate and fix.

Thank you.

**Comment by Crispin-at-Linknode** [comment]
See below for a sample of the model for a notifications API. This indeed passes the schema, however in the Amazon skill publication are it will fail the "Functional Test" validation with an SSL warning.

To pass, I had to add the "sslCertificateType" not only to the apis/custom/endpoint/uri but ALSO to the events/endpoint/uri and the regions/EU/endpoint/uri e.g.

    "regions": {
      "EU": {
        "endpoint": {
          "uri": "https://alexaproactiveevents.azurewebsites.net/api/Function1",
          "sslCertificateType": "Wildcard"
        }
      }
    }

When I used the current head of Alexa.NET.Management.UWPApp that references Alexa.NET.Management I could not edit the model and "Publish Model" until I did some code hacking to add sslCertificateType to these endpoints.

I hope that's clearer. It's a bind to create a new skill to test it all out on I know.


Model as per head support of .NET.Management
…
  "permissions": [
    {
      "name": "alexa::devices:all:notifications:write"
    }
  ],
  "events": {
    "publications": [
      {
        "eventName": "AMAZON.WeatherAlert.Activated"
      },
      {
        "eventName": "AMAZON.MessageAlert.Activated"
      }
    ],
    "endpoint": {
      "uri": "https://api.eu.amazonalexa.com/v1/proactiveEvents/stages/development"
    },
    "subscriptions": [
      {
        "eventName": "SKILL_PROACTIVE_SUBSCRIPTION_CHANGED"
      }
    ],
    "regions": {
      "EU": {
        "endpoint": {
          "uri": "https://api.eu.amazonalexa.com/v1/proactiveEvents/stages/development"
        }
      }
	}
  }
}

**Comment by stoiveyp** [comment]
That's much clearer, thank you 👍 

I'll try and take a look as soon as I can

**Comment by stoiveyp** [comment]
@Crispin-at-Linknode The endpoints have been consolidated in v3.1.0 so they all have the SslCertificateType option. If there's any problem with the change then re-open the issue 👍

**Comment by Crispin-at-Linknode** [comment]
I think a partial success, but remaining issue may be due to a different schema update required.

I am reading the model via the Alexa.NET.Management.UWPApp sample project that helps with everything CLI/ASK

I see the events endpoint has the wildcard shown OK - big tick, thank you.
But the /events/regions can contain different endpoints for the EU, FE, US.  See my example from earlier (https://github.com/stoiveyp/Alexa.NET.Management/issues/51#issuecomment-501313940) has lost the EU Uri and Wildcard somewhere in the serialisation/deserialization when viewing with Alexa.NET.Management.UWPApp and Alexa.NET.Management

I did have an additional schema "hack" to add the EU region in my copy of the Alexa.Net.Management master but it wasn't a proper solution.
Maybe I don't need an EU within regions within the event as I already have a generic endpoint. But references I copied implied I do (eg https://github.com/skilltemplates/proactive-events-api/blob/master/skill.json)


 {
        "eventName": "AMAZON.Occasion.Updated"
      }
    ],
    "subscriptions": [
      {
        "eventName": "SKILL_PROACTIVE_SUBSCRIPTION_CHANGED"
      }
    ],
    "regions": {
      "EU": {
        "uri": null        // ***** LOST IN TRANSLATION, ALSO THE SSLCERTIFICATETYPE ******
      }
    }
  }
}

**Comment by Crispin-at-Linknode** [comment]
I can't find a "re-open" from my login side, so added an additional comment. Hope it makes sense.

 Thanks - Crispin



Crispin Hoult

Founder & CEO (Linknode Ltd, trading as TrueViewVisuals)



T:   0141 374 2741

M: 07703 442 059



www.trueviewvisuals.com<http://www.trueviewvisuals.com/>



[https://a8b03ffbc00ed4da54a1-0c6684360696717b63d89dbc0edb802c.ssl.cf1.rackcdn.com/icon-facebook_28x28.jpg]<https://www.facebook.com/linknode>

[https://a8b03ffbc00ed4da54a1-0c6684360696717b63d89dbc0edb802c.ssl.cf1.rackcdn.com/icon-twitter_28x28.jpg]<https://www.twitter.com/linknode8>

[https://a8b03ffbc00ed4da54a1-0c6684360696717b63d89dbc0edb802c.ssl.cf1.rackcdn.com/icon-linkedin_28x28.jpg]<https://www.linkedin.com/in/abigail-brownlee-8a50245/>

​

Linknode Ltd (SC 397104) :: 221 Baltic Chambers, 50 Wellington Street, Glasgow G2 6HJ



This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

________________________________

**Comment by stoiveyp** [comment]
Hi @Crispin-at-Linknode - the region endpoints were changed in v3.1.0:

https://github.com/stoiveyp/Alexa.NET.Management/blob/master/Alexa.NET.Management/Api/CustomApi.cs#L12
https://github.com/stoiveyp/Alexa.NET.Management/blob/master/Alexa.NET.Management/Api/CustomApiRegion.cs#L8

If this isn't what you're referring to, or there's a particular issue with your skills, then could you please supply code/screenshots/links so that I have a better idea of the issue you're experiencing 👍

**Comment by Crispin-at-Linknode** [comment]
Steps to replicate, hopefully readable:

1) Checkout stoiveyp/Alexa.NET.Management.UWPApp  (and ensure nuget packages are most recent Alexa.NET.Management)

2) Create a new Skill

3) Run  Alexa.NET.Management.UWPApp  - observe model as per image "Skill51-A"
![Skill51-A](https://user-images.githubusercontent.com/22054739/59445096-ebdb4d80-8df6-11e9-94c3-79b20f98b886.png)

4) Add JSON to model to support notifications - as per image "Skills51-B"
    (JSON snippet can be copied from https://github.com/stoiveyp/Alexa.NET.Management/issues/51#issuecomment-501313940 and add sslCertificateType)
![Skill51-B](https://user-images.githubusercontent.com/22054739/59445711-02ce6f80-8df8-11e9-8beb-363f8b569f1f.png)

5) Put breakpoint on line 36 of StageModel.xaml.cs
            await ((SkillSummaryViewModel) this.DataContext).SetSkill(events);

6) Use VS variable watch on "manifest" to see how DeserialiseObject on Manifest.Text isn't deserialising properly resulting in null for the endpoint and sslCertificate

7) Leading to failure to commit change to model with Amazon error:

{"message":"Skill manifest is not valid.","violations":[{"message":"events.regions.EU - object has missing required properties ([\"endpoint\"])"}]}

**Comment by stoiveyp** [comment]
Event region fixed in v3.2.2
