### ISSUE TITLE
More PublicationStatus Enums

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [stoiveyp/Alexa.NET.Management#53]
When running with the Alexa.NET.Management.UWPApp sample utility (very useful) app I get an exception thrown on building the skills list due to some other/new status types in my skills list: 

Skills/PublicationStatus.cs requires a couple of additional values in the Enum

        REMOVED,
        HIDDEN

**Comment by stoiveyp** [comment]
Hi @crispin-at-linknode, could you please point me to some documentation or let me know what has happened to those skills to be in that state so I can try and recreate. Thank you :+1:

**Comment by Crispin-at-Linknode** [comment]
Documentation! I don't know what Amazon do to skills (or what I do to skills). Removed I think is easy as I have deleted some trial skills from the developer portal. Hidden may be once you have multiple published versions and the latest replaces the previous but I am guessing on the reason... just reporting what I am seeing. I can keep my version for now as I understand reluctance to make changes to code without evidence

**Comment by stoiveyp** [comment]
I hope you can appreciate that it would be unprofessional of me to make a change to a package that's in active use by others without a way of testing both the accuracy of the request and the expected outcome. Normally I'll spend my own time on the outcome - but to do that I need a way of verifying the request.

In this case your information about removing skills led to this document:
https://developer.amazon.com/docs/smapi/skill-certification-operations.html#hide-remove-unpublish

Your request for status additions were actually part of a bigger update, the Alexa team added support for the ability to unpublish (hide/remove) skills, something that wasn't available in the package previously.

This is now available in v3.2.0, I've also updated the UWPApp to start using the latest version
