### ISSUE TITLE
Delete a Skill missing

### ISSUE THREAD

**Issue by daledev-uk** [stoiveyp/Alexa.NET.Management#63]
Is it possible to add a method to Delete a skill to `ISkillManagementApi`, `SkillManagementApi` and `IClientSkillManagementApi` ?

Looks like it exists, ASK CLI uses something like `https://api.amazonalexa.com/v1/skills/{skillID}` sorry, can't find documentation to that delete method

**Comment by stoiveyp** [comment]
Not a problem, I found it - v3.9.0 now has a Delete method in Skills section of the API 👍 
https://www.nuget.org/packages/Alexa.NET.Management/3.9.0

**Comment by daledev-uk** [comment]
That's great, thanks!
