### ISSUE TITLE
Add reference-based catalog api

### ISSUE THREAD

**Issue by dennis-kuypers-gcx** [stoiveyp/Alexa.NET.Management#73]
Docs: https://developer.amazon.com/en-US/docs/alexa/smapi/reference-based-catalog-management.html

careful: [Create Catalog](https://developer.amazon.com/en-US/docs/alexa/smapi/reference-based-catalog-management.html#http-method-and-url-path-1) is incorrectly documented. It is missing the `/v1/` at the beginning of the url :)

**Comment by stoiveyp** [comment]
I'll add this to my todo list - thanks for pointing it out 👍

**Comment by stoiveyp** [comment]
This is now supported in v5.5.0
https://www.nuget.org/packages/Alexa.NET.Management/5.5.0
