### ISSUE TITLE
CatalogManagement.CreateUpload Error converting value \"INGESTION\" to type 'Alexa.NET.Management.CatalogManagement.IngestionStepName

### ISSUE THREAD

**Issue by Andrey15-0** [stoiveyp/Alexa.NET.Management#82]
On Createing new Upload for catalog error occurs: 
{"Error converting value \"INGESTION\" to type 'Alexa.NET.Management.CatalogManagement.IngestionStepName'. Path 'ingestionSteps[0].name', line 1, position 242."}

Problem in object Alexa.NET.Management.CatalogManagement.IngestionStepName
    public enum IngestionStepName
    {
        Upload = 0,
        SchemaValidation = 1
    }

in returned object it has also **"name": "INGESTION",**

Json returned:
{
	"catalogId": "amzn1.ask-catalog.cat.078c8b00-ed69-4517-ab74-02cee5c17a15",
	"createdDate": "2021-02-15T13:56:52.890Z",
	"id": "amzn1.ask-catalog.upl.6a0e7ceb-c923-4619-bc6b-5de258853c0c",
	"ingestionSteps": [
		{
			"errors": [],
			"logUrl": "",
			**"name": "INGESTION",**
			"status": "PENDING"
		},
		{
			"errors": [],
			"logUrl": "",
			"name": "UPLOAD",
			"status": "PENDING"
		},
		{
			"errors": [],
			"logUrl": "",
			"name": "SCHEMA_VALIDATION",
			"status": "PENDING"
		}
	],
	"lastUpdatedDate": "2021-02-15T13:56:52.890Z",
	"presignedUploadParts": [
		{
			"partNumber": 1,
			"url": "url"
		}
	],
	"status": "PENDING"
}

**Comment by stoiveyp** [comment]
Hi @Andrey15-0, thanks for raising this.

No indication of this is in the documentation, which is why it got missed. I should be able to get a fix in place this evening (at work right now, so give it 4-6hrs?)

You might want to edit your initial comment to remove that partNumber url as it's pre-signed 👍

**Comment by Andrey15-0** [comment]
Thanks @stoiveyp, it sounds great! Also thanks for pointing partNumber url - edited.
Security is our priority 💯 )

**Comment by stoiveyp** [comment]
This has been added to v5.7.3, which has just been published
I'll keep this open until you're able to confirm the issue has been resolved

**Comment by Andrey15-0** [comment]
Thanks @stoiveyp.
Confirm issue has been resolved in v5.7.3
